describe('Swag Labs', () => {
  it('Login to Saucedemo Site', () => {
    cy.visit('https://www.saucedemo.com');
    cy.get('[data-test="username"]').should('be.visible').type('problem_user');  
    cy.get('[data-test="password"]').should('be.visible').type('secret_sauce');
    cy.wait(3000);
    cy.get('[data-test="login-button"]').should('be.visible').click();
    cy.url().should('include', '/inventory.html');
    cy.wait(3000);
    cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').should('be.visible').click();
    cy.wait(3000);
    cy.get('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').should('be.visible').click();
    cy.wait(3000);
    cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').should('be.visible').click();
    cy.wait(3000);
    cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').should('be.visible').click();
    cy.wait(3000);
    cy.get('[data-test="add-to-cart-sauce-labs-onesie"]').should('be.visible').click();
    cy.wait(3000);
    cy.get('[data-test="add-to-cart-test.allthethings()-t-shirt-(red)"]').should('be.visible').click();
    cy.get('.shopping_cart_badge').should('be.visible');
    cy.wait(3000);
    cy.get('[data-test="shopping-cart-link"]').should('be.visible').click();
    cy.url().should('include', '/cart.html');
    cy.get('.cart_item').should('exist');
    cy.wait(3000);
    cy.get('[data-test="remove-sauce-labs-backpack"]').should('be.visible').click();
    cy.get('.cart_item').should('exist');
    cy.wait(3000);
    cy.get('[data-test="checkout"]').should('be.visible').click();
    cy.url().should('include', '/checkout-step-one.html');
    cy.get('.checkout_info').should('be.visible');
    cy.get('[data-test="firstName"]').should('be.visible').type('Hassan');
    cy.get('[data-test="lastName"]').should('be.visible').type('Daou');
    cy.get('[data-test="postalCode"]').should('be.visible').type('12343');
    cy.wait(3000);
    cy.get('[data-test="continue"]').should('be.visible').click();
    cy.url().should('include', '/checkout-step-two.html');
    cy.get('.summary_info').should('be.visible');
    cy.wait(3000);
    cy.get('[data-test="finish"]').should('be.visible').click();
    cy.url().should('include', '/checkout-complete.html');
    cy.contains('Thank you for your order!').should('be.visible');
    cy.wait(3000);
    cy.get('.bm-menu').should('be.visible').click();
    cy.wait(3000);
    cy.get('[data-test="logout-sidebar-link"]').should('be.visible').click();
    cy.url().should('eq', 'https://www.saucedemo.com/');
    cy.get('[data-test="login-button"]').should('be.visible');
  });
});